---
title: "Washington Hikes"
author: "Don Marco Loleng (loleng2)"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(purrr)
```

```{r, message=FALSE}
# Get the Data

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2020-11-24')
tuesdata <- tidytuesdayR::tt_load(2020, week = 48)

hike_data <- tuesdata$hike_data

# Or read in the data manually

hike_data <- readr::read_rds(url('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-24/hike_data.rds'))
```

```{r}
unique(hike_data$location)
```


```{r}
clean_hike_data = hike_data %>%
  extract(location, c("region", "locale"), "(.*) -- (.*)", remove=FALSE) %>%
  extract(length, c("length", "type"), "(.*) miles, (.*)") %>%
  mutate(length = ifelse(type=="roundtrip", as.numeric(length), 2*as.numeric(length))) %>%
  mutate(type = ifelse(type=="one-way", "out and back", type)) %>%
  unnest(features) %>%
  mutate(temp=1) %>%
  pivot_wider(names_from = features, values_from = temp, values_fn = list(temp = list)) %>%
  unnest(everything()) %>%
  replace(is.na(.), 0) %>%
  mutate(region = ifelse(region == "0", location, region))
```

```{r}
clean_hike_data %>%
  filter(locale == 0)
```

```{r}
features_df = clean_hike_data %>%
  select("rating","Dogs allowed on leash", "Wildlife", "Good for kids", "Lakes", "Fall foliage", "Ridges/passes", "Established campsites", "Mountain views", "Old growth","Waterfalls","Wildflowers/Meadows","Rivers","Dogs not allowed","Coast","Summits") %>%
  filter(rating > 0)
```

```{r}
lr = lm(rating~., data = featues_df)
```

```{r}
lr
```


```{r}
df = hike_data %>%
  extract(location, c("region", "locale"), "(.*) -- (.*)", remove=FALSE) %>%
  extract(length, c("length", "type"), "(.*) miles, (.*)") %>%
  mutate(length = ifelse(type=="roundtrip", as.numeric(length), 2*as.numeric(length))) %>%
  mutate(type = ifelse(type=="one-way", "out and back", type)) %>%
  unnest(features) %>%
  replace(is.na(.), 0) %>%
  mutate(region = ifelse(region == "0", location, region)) %>%
  select(region, features, rating)
  # group_by(region) %>%
  # summarise_all(list(sum))
```

```{r, message=FALSE, error=FALSE, warning=FALSE, results='hide'}
p = ggplot(data = df, aes(features)) +
  geom_bar(aes(fill=region), color = "black") +
  coord_flip() +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal() + 
  ggtitle("Hikes by Feature and Region")

ggsave("wahikes by feature and region", device = "png")
```


